default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  host: localhost
  username: postgres

development:
  <<: *default
  database: hanpuku_dev

test:
  <<: *default
  database: hanpuku_test

production:
  <<: *default
  database: hanpuku_production
