# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e26a19e732c343b34c06f678864f3c65aebb966b2f82908269fdf0c4e69a6dccedeaef2ffa86c902f24c62a19da1377aa3233612d4abb8949405806715395f31

test:
  secret_key_base: 3333cdbd57497b5cf547ae658ba62f46a0bf66d792ecc5bde631a5fe116eb15cda2ee724dc5f259aa079c324374ee145b581eb8c471f9e25a2ddc358b542d965

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
